version: '3'
services:
  db:
    ports:
      - 3306:3306
    image: mysql:8.0.30
    #platform: linux/x86_64
    command: --default-authentication-plugin=mysql_native_password

    volumes:
      - ./db/init:/docker-entrypoint-initdb.d
    environment:
      MYSQL_DATABASE: db
      MYSQL_ROOT_PASSWORD: password
      MYSQL_NAME: django
      MYSQL_USER: django
      MYSQL_PASSWORD: django
      TZ: 'Asia/Tokyo'

  web:
    build: .
    command: sh -c "./wait-for-it.sh db:3306; python3 manage.py runserver 0.0.0.0:8000"
    environment:
      MYSQL_DATABASE: db
      MYSQL_USER: django
      MYSQL_PASSWORD: django
    volumes:
      - .:/app
      - ./db/cnf.d:/etc/mysql/conf.d
    ports:
      - "8000:8000"
    depends_on:
      - db
