# Generated by Django 4.0.6 on 2022-08-10 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mathhub', '0003_question'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='body',
            field=models.TextField(default='body'),
        ),
        migrations.AlterField(
            model_name='question',
            name='title',
            field=models.CharField(default='title', max_length=255),
        ),
    ]
